### ISSUE TITLE
Maybe we could drop the lager dependency

### ISSUE THREAD

**Issue by whatyouhide** [joedevivo/hpack#11]
Digging into the code, I realized that while `hpack` depends on `lager`, it only actually logs something via `lager` **twice** ([here](https://github.com/joedevivo/hpack/blob/d903a08c1ef60f754402ee121ce5baaf0cc295cd/src/hpack.erl#L146) and [here](https://github.com/joedevivo/hpack/blob/d903a08c1ef60f754402ee121ce5baaf0cc295cd/src/hpack.erl#L176)). In both cases, it's some erroneous case: either we `throw` or we return a compression error, but never just ignore the case.

So, I propose we drop the dependency on lager and encode the information that we log today into the error message. For example, instead of 

``` erlang
decode(<<B:1,_/binary>>, _HeaderAcc, _Context) ->
    lager:debug("Bad header packet ~p", [B]),
    {error, compression_error}.
```

we could have

``` erlang
decode(<<B:1,_/binary>>, _HeaderAcc, _Context) ->
  {error, {compression_error, {bad_header_packet, B}}}.
```

We can let the caller decide what to do with this then. If they don't care, they'll just match on `{error, {compression_error, _}}` (or, even more often I believe, on `{error, _}`).

IMO, this has the benefit of:
- having one less dependency of course :)
- not creating easy dependency resolution conflicts when some HTTP/2 library other than chatterbox uses depends on hpack and lager (which I feel would be both common dependencies for a HTTP/2 library)
- this library becomes even more functional as another side effect would be gone

Wdyt @joedevivo? :)

**Comment by whatyouhide** [comment]
Ping @joedevivo?

**Comment by tsloughter** [comment]
Yea, I'd have to agree with this.
